<a href="https://colab.research.google.com/github/Terrykamau/Terrykamau/blob/main/MATRICES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
m1=np.array([[2,5],[3,8]])
print(m1)

[[2 5]
 [3 8]]


In [4]:
m1.shape

(2, 2)

In [6]:
m2=np.array([[6,4],[3,7],[88,99]])
print(m2)

[[ 6  4]
 [ 3  7]
 [88 99]]


In [7]:
random_matrix=np.random.rand(3,2)
print(random_matrix)

[[0.5111353  0.36952683]
 [0.67308974 0.30575184]
 [0.82623846 0.64574236]]


In [9]:
random_m2=np.random.randint(50,size=(4,4))
print(random_m2)

[[ 4  3 45 34]
 [25 27  2 42]
 [21 15 21 20]
 [19 46  5 38]]


In [10]:
m3=np.ones((3,3))
print(m3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
m4=np.ones((2,3),dtype=int)
print(m4)

[[1 1 1]
 [1 1 1]]


In [15]:
m5=np.zeros((1,2))
print(m5)

[[0. 0.]]


In [16]:
m7=np.eye(4,2)
print(m7)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


In [18]:
Transpose=np.transpose(m7)
print(Transpose)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [19]:
a=np.array([[2,4],[3,6]])
b=np.array([[5,7],[8,9]])
c=a+b
print(c)

[[ 7 11]
 [11 15]]


In [20]:
a=np.random.randint(30,size=(3,3))
b=np.random.randint(10,size=(3,3))
print(a)
print(b)
sum=np.add(a,b)
print(sum)

[[ 4  4 26]
 [21  7 23]
 [25 14 23]]
[[6 8 9]
 [4 4 8]
 [5 8 6]]
[[10 12 35]
 [25 11 31]
 [30 22 29]]


In [23]:
e=np.array([[3,2],[4,6]])
f=np.array([[4,3],[5,7]])
h=np.subtract(e,f)
print(h)

[[-1 -1]
 [-1 -1]]


In [24]:
k=np.array([[6,7],[8,9]])
n=7*k
print(n)

[[42 49]
 [56 63]]


In [26]:
k=np.array([[6,7],[8,9]])
h=np.multiply(4,k)
print(h)

[[24 28]
 [32 36]]


In [28]:
e=np.array([[3,2],[4,6],[7,8]])
f=np.array([[4,3],[5,7],[7,5]])
y=np.multiply(e,f)
print(e)
print(f)
print(y)

[[3 2]
 [4 6]
 [7 8]]
[[4 3]
 [5 7]
 [7 5]]
[[12  6]
 [20 42]
 [49 40]]
