<a href="https://colab.research.google.com/github/Terrykamau/Terrykamau/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
list=[i for i in range (100)]
start_time=process_time()
list=[i+5 for i in list]
end_time=process_time()
print(end_time-start_time)

0.00019974399999966863


In [ ]:
array=np.array([i for i in range (100)])
start_time=process_time()
array+=5
end_time=process_time()
print(end_time-start_time)

0.0013014909999995439


In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
a=np.array([1,2,3])
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [ ]:
a.shape

(3,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
x=np.zeros((3,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
y=np.ones((3,2))
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
m=np.full((5,4),3)
print(m)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
o=np.random.random((2,4))
print(o)

[[0.43249331 0.37128503 0.69124222 0.22850501]
 [0.26901683 0.64955318 0.6514203  0.0143225 ]]


In [ ]:
w=np.random.randint(10,50,(3,5))
print(w)

[[15 27 43 24 10]
 [49 32 42 16 37]
 [46 18 10 32 27]]


In [ ]:
t=np.linspace(10,40,5)
print(t)

[10.  17.5 25.  32.5 40. ]


In [ ]:
r=np.arange(10,50,5)
print(r)

[10 15 20 25 30 35 40 45]


In [ ]:
list=[10,20,30]
np_array=np.asarray(list)
print(np_array)
type(np_array)

[10 20 30]


numpy.ndarray

In [ ]:
e = np.random.randint(10,50,(5,5))
print(e)

[[41 39 44 43 31]
 [38 10 24 30 33]
 [35 20 45 49 27]
 [26 41 35 35 40]
 [11 27 20 42 47]]


In [ ]:
print(e.ndim)

2
2


In [ ]:
print(e.size)

25


In [ ]:
print(e.dtype)

int64


In [ ]:
import numpy as np
a = np.random.randint(5,15,(3,3))
b = np.random.randint(0,10,(3,3))
print(a)
print(b)

[[ 5 14  6]
 [ 5 11  7]
 [ 9 12  5]]
[[1 2 4]
 [5 3 8]
 [6 2 0]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 6 16 10]
 [10 14 15]
 [15 14  5]]
[[ 4 12  2]
 [ 0  8 -1]
 [ 3 10  5]]
[[ 5 28 24]
 [25 33 56]
 [54 24  0]]
[[5.         7.         1.5       ]
 [1.         3.66666667 0.875     ]
 [1.5        6.                inf]]


<ipython-input-7-863c63bc6d1d>:4: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(a,b))


In [ ]:
v=np.random.randint(9,18,(2,3))
print(v)
print(v.shape)


[[10 12 14]
 [14  9 10]]
(2, 3)


In [ ]:
trans=np.transpose(v)
print(trans)
print(trans.shape)

[[10 14]
 [12  9]
 [14 10]]
(3, 2)


In [ ]:
v=np.random.randint(9,18,(2,3))
print(v)
print(v.shape)


[[12 16  9]
 [12 12 15]]
(2, 3)


In [ ]:
w=v.T
print(w)
print(w.shape)

[[12 12]
 [16 12]
 [ 9 15]]
(3, 2)


In [ ]:
a=np.random.randint(10,50,(3,4))
print(a)

[[46 34 26 38]
 [49 24 11 22]
 [10 35 30 41]]


In [ ]:
b=a.reshape(4,3)
print(b)
print(b.shape)

[[46 34 26]
 [38 49 24]
 [11 22 10]
 [35 30 41]]
(4, 3)
